---
# Hierr√ºber werden die Automatisierungen gesteuert
#
# https://www.home-assistant.io/docs/automation/
#
automation: !include ../automations.yaml
automation split: !include_dir_list ../automations
